Add better output for Branch Management (#68)

diff --git a/github-branches/action.yaml b/github-branches/action.yaml
--- a/github-branches/action.yaml
+++ b/github-branches/action.yaml
@@ -28,25 +28,30 @@ runs:
         echo "# Branch ${{ inputs.action }} summary ${{ inputs.dry-run == 'true' && '(Dry Run)' || '' }}" >> $GITHUB_STEP_SUMMARY
         echo "| Repository | Branch | Status |" >> $GITHUB_STEP_SUMMARY
         echo "| :--- | :--- | :--- |" >> $GITHUB_STEP_SUMMARY
+        gh auth setup-git
 
         # Perform Actions
-        for repository in $(jq -r '.[]' <<< '${{ inputs.repositories }}'); do
-          echo "${{ inputs.action }} ${{ inputs.branch-name }} on ${repository}"
-          gh auth setup-git
-          if [[ $(awk '{print length}' <<< $(git ls-remote --heads --tags https://github.com/dvsa/${repository} ${{ inputs.branch-name }})) ${{ inputs.action == 'delete' && '==' || '>' }} 0 ]]; then
-            echo "| ${repository} | ${{ inputs.branch-name }} | ☑️ ${{ inputs.action == 'delete' && 'Does not Exist' || 'Already Exists' }} |" >> $GITHUB_STEP_SUMMARY
+        manage_branch () {
+          if [[ $(awk '{print length}' <<< $(git ls-remote --heads --tags https://github.com/dvsa/$1 ${{ inputs.branch-name }})) ${{ inputs.action == 'delete' && '==' || '>' }} 0 ]]; then
+            echo "| $1 | ${{ inputs.branch-name }} | ☑️ ${{ inputs.action == 'delete' && 'Does not Exist' || 'Already Exists' }} |" >> $GITHUB_STEP_SUMMARY
 
           else
             if [[ "${{ inputs.action }}" == "Create" ]]; then
-              commit_id=$(awk '{sub(/[^a-f0-9]+.*/,"",$0); print $0}' <<< $(git ls-remote --heads --tags https://github.com/dvsa/${repository} ${{ inputs.branch-source }}))
-              ${{ inputs.dry-run == 'true' && 'echo ' || '' }}gh api -X POST /repos/dvsa/${repository}/git/refs -f ref='refs/heads/${{ inputs.branch-name }}' -f sha="${commit_id}" && { echo "| ${repository} | ${{ inputs.branch-name }} | ✅ Created |" >> $GITHUB_STEP_SUMMARY; } || { echo "| ${repository} | ${{ inputs.branch-name }} | ❌ Failed |" >> $GITHUB_STEP_SUMMARY; }
+              commit_id=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/dvsa/$1/branches/${{ inputs.branch-source }} | jq -r '.commit.sha')
+              ${{ inputs.dry-run == 'true' && 'echo [debug] ' || '' }}gh api -X POST /repos/dvsa/$1/git/refs -f ref='refs/heads/${{ inputs.branch-name }}' -f sha="${commit_id}" ${{ inputs.dry-run != 'true' && '1>/dev/null' || '' }} && { echo "| $1 | ${{ inputs.branch-name }} | ✅ Created |" >> $GITHUB_STEP_SUMMARY; } || { echo "| $1 | ${{ inputs.branch-name }} | ❌ Failed |" >> $GITHUB_STEP_SUMMARY; }
                 
             elif [[ "${{ inputs.action }}" == "Delete" ]]; then
-              ${{ inputs.dry-run == 'true' && 'echo ' || '' }}gh api -X DELETE /repos/dvsa/${repository}/git/refs/heads/${{ inputs.branch-name }} && { echo "| ${repository} | ${{ inputs.branch-name }} | ✅ Deleted |" >> $GITHUB_STEP_SUMMARY; } || { echo "| ${repository} | ${{ inputs.branch-name }} | ❌ Failed |" >> $GITHUB_STEP_SUMMARY; }
+              ${{ inputs.dry-run == 'true' && 'echo [debug] ' || '' }}gh api -X DELETE /repos/dvsa/$1/git/refs/heads/${{ inputs.branch-name }} ${{ inputs.dry-run != 'true' && '1>/dev/null' || '' }} && { echo "| $1 | ${{ inputs.branch-name }} | ✅ Deleted |" >> $GITHUB_STEP_SUMMARY; } || { echo "| $1 | ${{ inputs.branch-name }} | ❌ Failed |" >> $GITHUB_STEP_SUMMARY; }
 
             else
               echo "❌ Invalid action requested: `${{ inputs.action }}`" >> $GITHUB_STEP_SUMMARY
               exit 99
             fi
           fi
+          printf "➡️ \033[0;34m${{ inputs.action }}d \033[0m${{ inputs.branch-name }} \033[0;34mon \033[0m$1\n"
+        }
+
+        for repository in $(jq -r '.[]' <<< '${{ inputs.repositories }}'); do
+          manage_branch $repository &
         done
+        wait
